package programa;
// Generated 05-mar-2017 0:03:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Consulta generated by hbm2java
 */
public class Consulta  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String horario;
     private String nombreProfesional;
     private String numConsulta;
     private String visible;
     private Set pacientes = new HashSet(0);

    public Consulta() {
    }

	
    public Consulta(String nombre, String horario, String nombreProfesional, String numConsulta, String visible) {
        this.nombre = nombre;
        this.horario = horario;
        this.nombreProfesional = nombreProfesional;
        this.numConsulta = numConsulta;
        this.visible = visible;
    }
    public Consulta(String nombre, String horario, String nombreProfesional, String numConsulta, String visible, Set pacientes) {
       this.nombre = nombre;
       this.horario = horario;
       this.nombreProfesional = nombreProfesional;
       this.numConsulta = numConsulta;
       this.visible = visible;
       this.pacientes = pacientes;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getHorario() {
        return this.horario;
    }
    
    public void setHorario(String horario) {
        this.horario = horario;
    }
    public String getNombreProfesional() {
        return this.nombreProfesional;
    }
    
    public void setNombreProfesional(String nombreProfesional) {
        this.nombreProfesional = nombreProfesional;
    }
    public String getNumConsulta() {
        return this.numConsulta;
    }
    
    public void setNumConsulta(String numConsulta) {
        this.numConsulta = numConsulta;
    }
    public String getVisible() {
        return this.visible;
    }
    
    public void setVisible(String visible) {
        this.visible = visible;
    }
    public Set getPacientes() {
        return this.pacientes;
    }
    
    public void setPacientes(Set pacientes) {
        this.pacientes = pacientes;
    }




}


