package programa;
// Generated 05-mar-2017 0:03:12 by Hibernate Tools 4.3.1



/**
 * Pacientesintoma generated by hbm2java
 */
public class Pacientesintoma  implements java.io.Serializable {


     private Integer id;
     private Paciente paciente;
     private Sintoma sintoma;
     private String visible;

    public Pacientesintoma() {
    }

    public Pacientesintoma(Paciente paciente, Sintoma sintoma, String visible) {
       this.paciente = paciente;
       this.sintoma = sintoma;
       this.visible = visible;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Paciente getPaciente() {
        return this.paciente;
    }
    
    public void setPaciente(Paciente paciente) {
        this.paciente = paciente;
    }
    public Sintoma getSintoma() {
        return this.sintoma;
    }
    
    public void setSintoma(Sintoma sintoma) {
        this.sintoma = sintoma;
    }
    public String getVisible() {
        return this.visible;
    }
    
    public void setVisible(String visible) {
        this.visible = visible;
    }




}


