package programa;
// Generated 05-mar-2017 0:03:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer id;
     private Consulta consulta;
     private String nombre;
     private String apellidos;
     private String dni;
     private String numSegSocial;
     private String direccion;
     private String telefono;
     private int edad;
     private String sexo;
     private String visible;
     private Set pacientesintomas = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(Consulta consulta, String nombre, String apellidos, String dni, String numSegSocial, String direccion, String telefono, int edad, String sexo, String visible) {
        this.consulta = consulta;
        this.nombre = nombre;
        this.apellidos = apellidos;
        this.dni = dni;
        this.numSegSocial = numSegSocial;
        this.direccion = direccion;
        this.telefono = telefono;
        this.edad = edad;
        this.sexo = sexo;
        this.visible = visible;
    }
    public Paciente(Consulta consulta, String nombre, String apellidos, String dni, String numSegSocial, String direccion, String telefono, int edad, String sexo, String visible, Set pacientesintomas) {
       this.consulta = consulta;
       this.nombre = nombre;
       this.apellidos = apellidos;
       this.dni = dni;
       this.numSegSocial = numSegSocial;
       this.direccion = direccion;
       this.telefono = telefono;
       this.edad = edad;
       this.sexo = sexo;
       this.visible = visible;
       this.pacientesintomas = pacientesintomas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Consulta getConsulta() {
        return this.consulta;
    }
    
    public void setConsulta(Consulta consulta) {
        this.consulta = consulta;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellidos() {
        return this.apellidos;
    }
    
    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNumSegSocial() {
        return this.numSegSocial;
    }
    
    public void setNumSegSocial(String numSegSocial) {
        this.numSegSocial = numSegSocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public int getEdad() {
        return this.edad;
    }
    
    public void setEdad(int edad) {
        this.edad = edad;
    }
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }
    public String getVisible() {
        return this.visible;
    }
    
    public void setVisible(String visible) {
        this.visible = visible;
    }
    public Set getPacientesintomas() {
        return this.pacientesintomas;
    }
    
    public void setPacientesintomas(Set pacientesintomas) {
        this.pacientesintomas = pacientesintomas;
    }




}


