package programa;
// Generated 05-mar-2017 0:03:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sintoma generated by hbm2java
 */
public class Sintoma  implements java.io.Serializable {


     private Integer id;
     private String breveDescripcion;
     private String descripcion;
     private String nivelGravedad;
     private String visible;
     private Set pacientesintomas = new HashSet(0);

    public Sintoma() {
    }

	
    public Sintoma(String breveDescripcion, String descripcion, String nivelGravedad, String visible) {
        this.breveDescripcion = breveDescripcion;
        this.descripcion = descripcion;
        this.nivelGravedad = nivelGravedad;
        this.visible = visible;
    }
    public Sintoma(String breveDescripcion, String descripcion, String nivelGravedad, String visible, Set pacientesintomas) {
       this.breveDescripcion = breveDescripcion;
       this.descripcion = descripcion;
       this.nivelGravedad = nivelGravedad;
       this.visible = visible;
       this.pacientesintomas = pacientesintomas;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getBreveDescripcion() {
        return this.breveDescripcion;
    }
    
    public void setBreveDescripcion(String breveDescripcion) {
        this.breveDescripcion = breveDescripcion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNivelGravedad() {
        return this.nivelGravedad;
    }
    
    public void setNivelGravedad(String nivelGravedad) {
        this.nivelGravedad = nivelGravedad;
    }
    public String getVisible() {
        return this.visible;
    }
    
    public void setVisible(String visible) {
        this.visible = visible;
    }
    public Set getPacientesintomas() {
        return this.pacientesintomas;
    }
    
    public void setPacientesintomas(Set pacientesintomas) {
        this.pacientesintomas = pacientesintomas;
    }




}


